// This file is auto-generated by Vite
import { application } from "@hotwired/stimulus"

// Register all controllers in the controllers directory
const controllers = import.meta.globEager('./**/*_controller.js')
Object.values(controllers).forEach((controller) => {
  application.register(controller.name, controller.default)
})
