version: '3.8'

name: "stackoverflow_clone_definitive_edition"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - bundle:/usr/local/bundle
      - node_modules:/workspaces/${localWorkspaceFolderBasename}/node_modules
      - packs:/workspaces/${localWorkspaceFolderBasename}/public/packs
      - rails_cache:/workspaces/${localWorkspaceFolderBasename}/tmp/cache
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      RAILS_MAX_THREADS: 5
      EDITOR: code
      DATABASE_URL: postgres://postgres:postgres@postgres:5432
    user: vscode
    command: sleep infinity
    depends_on:
      postgres:
        condition: service_healthy
      selenium:
        condition: service_started
    networks:
      - development
    init: true
    security_opt:
      - no-new-privileges:true

  postgres:
    image: postgres:16.1-alpine
    restart: unless-stopped
    volumes:
      - ~/.postgres-data/stackoverflow_clone:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stackoverflow_clone_definitive_edition_development
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    user: postgres
    security_opt:
      - no-new-privileges:true

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped
    shm_size: '2gb'
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - development
    security_opt:
      - no-new-privileges:true

volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
  packs:
    driver: local
  rails_cache:
    driver: local

networks:
  development:
    driver: bridge
